[tool.black]
line-length = 79
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
(
    \.git
    | alembic
    | venv
    | \.venv
    | _build
    | buck-out
    | build
    | migrations
    | settings
    | wsgi
    | asgi
    | manage
    | \.pyc
    | \.pyo
    | \.pyd
    | \.db
    | \.bak
    | \.swp
    | \.log
    | \.sql
    | \.sqlite3
    | \.sqlite3-journal
    | ^setup\.py
    | ^__init__\.py
)
'''

[tool.pytest.ini_options]
pythonpath = ['.']
asyncio_mode = 'auto'
addopts = '-v -s -p no:warnings'
