services:
  backend:
    env_file:
      - path: .env
        required: true
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: cat_show_backend
    restart: on-failure
    depends_on:
      - db

  db:
    env_file:
      - path: .env
        required: true
    image: postgres:15-alpine
    container_name: cat_show_db
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginxinc/nginx-unprivileged:1.26.1-alpine
    container_name: cat_show_gateway
    volumes:
      - static_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - backend
    restart: always
    ports:
      - "8000:80"

networks:
  default:
    name: cat_show_network

volumes:
  db_data:
  static_data:
